# Generated by Django 5.2.17 on 2026-09-17 07:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('created', 'Создано'), ('sent', 'Приглашение отправлено'), ('started', 'В процессе'), ('completed', 'Завершено'), ('expired', 'Срок истёк'), ('revoked', 'Отозвано')], db_index=True, default='created', max_length=16)),
                ('bank_version', models.CharField(default='1.0.0-draft', editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attempt', to='assessment.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(choices=[('strategic_thinking', 'STRATEGIC_THINKING'), ('delegation', 'DELEGATION'), ('accountability', 'ACCOUNTABILITY'), ('communication', 'COMMUNICATION'), ('persistence', 'PERSISTENCE'), ('result_orientation', 'RESULT_ORIENTATION'), ('motivation', 'MOTIVATION'), ('composure', 'COMPOSURE'), ('management', 'MANAGEMENT')], max_length=32)),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level', models.CharField(choices=[('very_low', 'VERY_LOW'), ('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('very_high', 'VERY_HIGH')], max_length=16)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment.attempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'competency'), name='one_result_per_competency')],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=8)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.attempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question_id'), name='one_answer_per_question')],
            },
        ),
    ]
