# Generated by Django 5.2.17 on 2026-09-18 07:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='department',
            field=models.CharField(blank=True, choices=[('unit_1', 'Отделение 1'), ('unit_2', 'Отделение 2'), ('unit_3', 'Отделение 3'), ('unit_4', 'Отделение 4'), ('unit_5', 'Отделение 5'), ('unit_6', 'Отделение 6'), ('management', 'Департамент управления')], max_length=24),
        ),
        migrations.AddField(
            model_name='invitation',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invitation',
            name='participant_type',
            field=models.CharField(choices=[('employee', 'Действующий сотрудник'), ('candidate', 'Кандидат на трудоустройство')], default='employee', max_length=16),
        ),
        migrations.AddField(
            model_name='invitation',
            name='position',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='bank_version',
            field=models.CharField(default='2.0.0-pilot', editable=False, max_length=32),
        ),
        migrations.CreateModel(
            name='CognitiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=24)),
                ('correct', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_results', to='assessment.attempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'domain'), name='one_cognitive_result_per_domain')],
            },
        ),
    ]
