# Generated by Django 5.2.17 on 2026-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_attempt_consented_at_invitation_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='bank_version',
            field=models.CharField(default='2.1.0-pilot', editable=False, max_length=32),
        ),
    ]
