# Generated by Django 5.2.17 on 2026-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_invitation_bank_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='position_level',
            field=models.CharField(choices=[('leader', 'Руководитель'), ('staff', 'Специалист / менеджер / помощник')], default='staff', max_length=16),
        ),
    ]
