# Generated by Django 5.2.17 on 2026-09-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_invitation_position_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
    ]
